apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-10-19T14:50:05Z"
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie
  sessionAffinity: None
  type: LoadBalancer
