apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage           
  labels:
    app: nginx-storage          
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 1000"]
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi

